// me_amanda1.ysc @ L31978
void func_221()
{
  PED::SET_PED_AS_GROUP_MEMBER(iLocal_296, func_226());
  PED::SET_PED_GROUP_MEMBER_PASSENGER_INDEX(iLocal_296, 0);
  PED::SET_PED_NEVER_LEAVES_GROUP(iLocal_296, 1);
  PED::SET_PED_CAN_BE_TARGETTED(iLocal_296, false);
  PED::SET_PED_DIES_IN_WATER(iLocal_296, 0);
  PED::SET_PED_DIES_IN_SINKING_VEHICLE(iLocal_296, 0);
  AUDIO::DISTANT_COP_CAR_SIRENS(0);
}