// jewelry_setup1.ysc @ L106870
void func_526()
{
  if (CUTSCENE::IS_CUTSCENE_ACTIVE())
  {
    CUTSCENE::STOP_CUTSCENE(0);
  }
  CUTSCENE::REMOVE_CUTSCENE();
  AUDIO::RELEASE_MISSION_AUDIO_BANK();
  func_362(0);
  func_311();
  HUD::CLEAR_PRINTS();
  if (PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0))
  {
    ENTITY::SET_ENTITY_COORDS(PLAYER::PLAYER_PED_ID(), ENTITY::GET_ENTITY_COORDS(PLAYER::PLAYER_PED_ID(), true), 1, false, 0, 1);
  }
}