// am_mp_arena_garage.ysc @ L350649
void func_5345(int iParam0, vector3 vParam1)
{
  if (!ENTITY::DOES_ENTITY_EXIST(Local_378.f_433))
  {
    if (func_5365(iParam0, 1, 1))
    {
      if (!func_214())
      {
        Local_378.f_433 = PED::CREATE_PED(4, ENTITY::GET_ENTITY_MODEL(PLAYER::GET_PLAYER_PED(iParam0)), ENTITY::GET_ENTITY_COORDS(PLAYER::GET_PLAYER_PED(iParam0), true) + vParam1, ENTITY::GET_ENTITY_HEADING(PLAYER::GET_PLAYER_PED(iParam0)), 0, false);
      }
      else
      {
        Local_378.f_433 = PED::CREATE_PED(5, ENTITY::GET_ENTITY_MODEL(PLAYER::GET_PLAYER_PED(iParam0)), ENTITY::GET_ENTITY_COORDS(PLAYER::GET_PLAYER_PED(iParam0), true) + vParam1, ENTITY::GET_ENTITY_HEADING(PLAYER::GET_PLAYER_PED(iParam0)), 0, false);
      }
      PED::CLONE_PED_TO_TARGET(PLAYER::GET_PLAYER_PED(iParam0), Local_378.f_433);
      if (INTERIOR::IS_VALID_INTERIOR(INTERIOR::GET_INTERIOR_FROM_ENTITY(PLAYER::GET_PLAYER_PED(iParam0))))
      {
        if (INTERIOR::IS_INTERIOR_READY(INTERIOR::GET_INTERIOR_FROM_ENTITY(PLAYER::GET_PLAYER_PED(iParam0))))
        {
          INTERIOR::FORCE_ROOM_FOR_ENTITY(Local_378.f_433, INTERIOR::GET_INTERIOR_FROM_ENTITY(PLAYER::GET_PLAYER_PED(iParam0)), INTERIOR::GET_ROOM_KEY_FROM_ENTITY(PLAYER::GET_PLAYER_PED(iParam0)));
        }
      }
      ENTITY::FREEZE_ENTITY_POSITION(Local_378.f_433, true);
      WEAPON::SET_CURRENT_PED_WEAPON(Local_378.f_433, joaat("WEAPON_UNARMED"), true);
      PED::SET_FORCE_FOOTSTEP_UPDATE(Local_378.f_433, 1);
    }
  }
}