// fmmc_launcher.c @ L572829
void func_9230()
{
  PED::REMOVE_ACTION_MODE_ASSET("TREVOR_ACTION");
  PED::REMOVE_ACTION_MODE_ASSET("MICHAEL_ACTION");
  PED::REMOVE_ACTION_MODE_ASSET("FRANKLIN_ACTION");
}