// fbi4.c @ L126199
void func_804()
{
  if (!iLocal_507)
  {
    if (MISC::GET_DISTANCE_BETWEEN_COORDS(ENTITY::GET_ENTITY_COORDS(PLAYER::PLAYER_PED_ID(), true), 882.5773f, -2347.359f, 29.3307f, true) > 250f)
    {
      PLAYER::CLEAR_PLAYER_WANTED_LEVEL(PLAYER::PLAYER_ID());
      MISC::SET_FAKE_WANTED_LEVEL(0);
      PLAYER::SET_MAX_WANTED_LEVEL(1);
      PED::SET_CREATE_RANDOM_COPS(false);
      PLAYER::SET_WANTED_LEVEL_MULTIPLIER(0.1f);
      func_523();
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(1, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(2, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(4, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(12, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(7, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(8, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(9, false);
      MISC::BLOCK_DISPATCH_SERVICE_RESOURCE_CREATION(10, false);
      iLocal_507 = 1;
    }
  }
}