// chinese1.ysc @ L111618
int func_606()
{
  if ((((((STREAMING::HAS_MODEL_LOADED(func_91(2)) && STREAMING::HAS_MODEL_LOADED(Local_300.f_1)) && STREAMING::HAS_MODEL_LOADED(Local_304.f_1)) && STREAMING::HAS_MODEL_LOADED(func_523(2, 0))) && VEHICLE::HAS_VEHICLE_ASSET_LOADED(Local_315.f_1)) && STREAMING::HAS_MODEL_LOADED(Local_329[0 /*24*/].f_2)) && STREAMING::HAS_ANIM_DICT_LOADED(sLocal_576))
  {
    return 1;
  }
  return 0;
}