// fbi5a.ysc @ L135734
void func_936()
{
  iLocal_671 = INTERIOR::GET_INTERIOR_AT_COORDS(vLocal_613);
  STREAMING::REQUEST_MODEL(Local_65[0 /*25*/].f_1);
  STREAMING::REQUEST_MODEL(Local_64[0 /*25*/].f_1);
  STREAMING::REQUEST_MODEL(Local_170.f_2);
  STREAMING::REQUEST_MODEL(Local_295[0 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(Local_295[1 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(Local_295[2 /*24*/].f_2);
  STREAMING::REQUEST_MODEL(WEAPON::GET_WEAPONTYPE_MODEL(joaat("WEAPON_CARBINERIFLE")));
  WEAPON::REQUEST_WEAPON_ASSET(joaat("WEAPON_CARBINERIFLE"), 31, 0);
  STREAMING::REQUEST_MODEL(WEAPON::GET_WEAPONTYPE_MODEL(joaat("WEAPON_STUNGUN")));
  WEAPON::REQUEST_WEAPON_ASSET(joaat("WEAPON_STUNGUN"), 31, 0);
  AUDIO::PREPARE_ALARM("FIB_05_BIOTECH_LAB_ALARMS");
  AUDIO::REQUEST_SCRIPT_AUDIO_BANK("SCRIPT\LIFTS", false, -1);
  STREAMING::REQUEST_ANIM_DICT("missfbi5ig_2");
  PED::REQUEST_ACTION_MODE_ASSET("MICHAEL_ACTION");
  PED::REQUEST_ACTION_MODE_ASSET("MP_FEMALE_ACTION");
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 0, 0, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 3, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 4, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 6, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 8, 4, 0);
  PED::SET_PED_PRELOAD_VARIATION_DATA(PLAYER::PLAYER_PED_ID(), 10, 0, 0);
  INTERIOR::PIN_INTERIOR_IN_MEMORY(iLocal_671);
}