// am_mp_hangar.ysc @ L344692
void func_5304()
{
  GRAPHICS::SET_STREAMED_TEXTURE_DICT_AS_NO_LONGER_NEEDED("LineArcadeMinigame");
  AUDIO::RELEASE_NAMED_SCRIPT_AUDIO_BANK("DLC_EXEC1/OFFICE_BOARDROOM");
  HUD::CLEAR_ADDITIONAL_TEXT(3, false);
  MISC::CLEAR_BIT(&Global_1662545, 6);
  MISC::CLEAR_BIT(&Global_1662545, 7);
}