// golf.ysc @ L128322
void func_1262()
{
  HUD::SET_MINIMAP_GOLF_COURSE_OFF();
  HUD::UNLOCK_MINIMAP_ANGLE();
  HUD::UNLOCK_MINIMAP_POSITION();
  HUD::SET_RADAR_ZOOM(0);
  if (!func_443())
  {
    HUD::TOGGLE_STEALTH_RADAR(1);
  }
}