// michael1.ysc @ L4204
void func_41()
{
  func_47();
  func_45();
  func_43();
  func_42(0);
  if (iLocal_388 == 1)
  {
    MISC::SET_WEATHER_TYPE_NOW_PERSIST("EXTRASUNNY");
    MISC::CLEAR_WEATHER_TYPE_PERSIST();
    MISC::_CLEAR_CLOUD_HAT();
  }
  else if (iLocal_388 == 0)
  {
    MISC::CLEAR_WEATHER_TYPE_PERSIST();
  }
  GRAPHICS::CLEAR_TIMECYCLE_MODIFIER();
  GRAPHICS::_RESET_EXTRA_TIMECYCLE_MODIFIER_STRENGTH();
  VEHICLE::_0x35E0654F4BAD7971(1);
  VEHICLE::DELETE_ALL_TRAINS();
}