// paparazzo1.ysc @ L53596
void func_579()
{
  if (func_68(Local_531))
  {
    PED::SET_PED_COMPONENT_VARIATION(Local_531, 9, 1, 0, 0);
    PED::SET_PED_HELMET(Local_531, 0);
    ENTITY::SET_ENTITY_VISIBLE(Local_531, true, 0);
    PED::SET_PED_CAN_BE_TARGETTED(Local_531, false);
    PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(Local_531, 0);
    PED::ADD_ARMOUR_TO_PED(Local_531, 100);
    ENTITY::SET_ENTITY_LOAD_COLLISION_FLAG(Local_531, true, 1);
    PED::SET_PED_CAN_RAGDOLL_FROM_PLAYER_IMPACT(Local_531, 0);
    PED::SET_PED_CONFIG_FLAG(Local_531, 42, true);
    PED::SET_PED_CONFIG_FLAG(Local_531, 132, true);
    PED::SET_PED_CONFIG_FLAG(Local_531, 118, true);
    PED::SET_PED_CONFIG_FLAG(Local_531, 167, true);
    PED::SET_PED_CONFIG_FLAG(Local_531, 185, true);
    PED::SET_PED_CAN_RAGDOLL_FROM_PLAYER_IMPACT(Local_531, 0);
    PED::SET_PED_DIES_IN_WATER(Local_531, 1);
    PED::SET_PED_DIES_IN_SINKING_VEHICLE(Local_531, 1);
    PED::SET_PED_MAX_TIME_IN_WATER(Local_531, 2f);
    PED::SET_PED_MAX_TIME_UNDERWATER(Local_531, 2f);
    TASK::SET_PED_PATH_PREFER_TO_AVOID_WATER(Local_531, 1);
    if (PED::IS_PED_IN_GROUP(Local_531))
    {
      PED::REMOVE_PED_FROM_GROUP(Local_531);
    }
    PED::SET_PED_RELATIONSHIP_GROUP_HASH(Local_531, iLocal_346);
    PED::SET_BLOCKING_OF_NON_TEMPORARY_EVENTS(Local_531, true);
    func_565(&uLocal_366, 3, Local_531, "BEVERLY", 0, 1);
    PED::SET_PED_CAN_USE_AUTO_CONVERSATION_LOOKAT(Local_531, 1);
  }
}