// fm_bj_race_controler.ysc @ L287360
void func_3971(var uParam0)
{
  int iVar0;
  
  PAD::DISABLE_CONTROL_ACTION(2, 230, 1);
  WEAPON::SET_CURRENT_PED_WEAPON(PLAYER::PLAYER_PED_ID(), joaat("WEAPON_UNARMED"), false);
  PED::SET_PED_CAN_SWITCH_WEAPON(PLAYER::PLAYER_PED_ID(), false);
  if (PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0) && !func_238(uParam0))
  {
    iVar0 = PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), 0);
    if (VEHICLE::DOES_VEHICLE_HAVE_WEAPONS(iVar0))
    {
      VEHICLE::DISABLE_VEHICLE_WEAPON(1, joaat("VEHICLE_WEAPON_PLAYER_LASER"), iVar0, PLAYER::PLAYER_PED_ID());
      VEHICLE::DISABLE_VEHICLE_WEAPON(1, joaat("VEHICLE_WEAPON_RUINER_BULLET"), iVar0, PLAYER::PLAYER_PED_ID());
      VEHICLE::DISABLE_VEHICLE_WEAPON(1, joaat("VEHICLE_WEAPON_RUINER_ROCKET"), iVar0, PLAYER::PLAYER_PED_ID());
      VEHICLE::_SET_VEHICLE_WEAPON_CAPACITY(iVar0, 0, 0);
    }
  }
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 422, true);
}