// arena_carmod.ysc @ L297768
int func_2638()
{
  if (!PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0))
  {
    if ((!NETWORK::NETWORK_IS_IN_MP_CUTSCENE() && !func_1359(PLAYER::PLAYER_ID())) && !Global_1676851)
    {
      MISC::CLEAR_BIT(&iLocal_167, 7);
    }
  }
  else if (((((((((((func_2634() || !func_279(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), 0), 1)) || PAD::GET_DISABLED_CONTROL_UNBOUND_NORMAL(0, 71) != 0f) || PAD::GET_DISABLED_CONTROL_UNBOUND_NORMAL(0, 72) != 0f) || PAD::IS_CONTROL_PRESSED(0, 71)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(0, 71)) || PAD::IS_DISABLED_CONTROL_PRESSED(0, 71)) || PAD::IS_CONTROL_JUST_PRESSED(0, 72)) || PAD::IS_CONTROL_PRESSED(0, 72)) || PAD::IS_DISABLED_CONTROL_JUST_PRESSED(0, 72)) || PAD::IS_DISABLED_CONTROL_PRESSED(0, 72)) || !func_2239(ENTITY::GET_ENTITY_MODEL(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), 0))))
  {
    return 0;
  }
  if ((((((((((PED::GET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 113) || func_2634()) || func_2579(PLAYER::PLAYER_ID())) || PED::GET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 373)) || !func_190(PLAYER::PLAYER_ID(), -1)) || MISC::IS_BIT_SET(iLocal_167, 7)) || INTERIOR::GET_ROOM_KEY_FROM_ENTITY(PLAYER::PLAYER_PED_ID()) != -1198215017) || func_2470()) || TASK::GET_SCRIPT_TASK_STATUS(PLAYER::PLAYER_PED_ID(), 451360105) == 1) || TASK::GET_SCRIPT_TASK_STATUS(PLAYER::PLAYER_PED_ID(), 451360105) == 0) || TASK::GET_IS_TASK_ACTIVE(PLAYER::PLAYER_PED_ID(), 2))
  {
    return 0;
  }
  if (Global_262145.f_24148)
  {
    return 0;
  }
  return 1;
}