// fm_bj_race_controler.ysc @ L277962
void func_3725()
{
  if (PAD::IS_CONTROL_PRESSED(2, 79) || PAD::IS_CONTROL_PRESSED(2, 231))
  {
    NETWORK::NETWORK_SET_LOCAL_PLAYER_SYNC_LOOK_AT(1);
  }
  else
  {
    NETWORK::NETWORK_SET_LOCAL_PLAYER_SYNC_LOOK_AT(0);
  }
}