// am_mp_shooting_range.ysc @ L118517
void func_904()
{
  if (Local_1552 != 2)
  {
    Stack.Push(&Local_1552);
    Call_Loc(Local_1538.f_8);
  }
  func_873(0, 0);
  MISC::CLEAR_BIT(&(Global_1676879.f_1), 18);
  PLAYER::SET_PLAYER_INVINCIBLE(PLAYER::PLAYER_ID(), 0);
  PLAYER::SET_PLAYER_LOCKON(PLAYER::PLAYER_ID(), 1);
  PLAYER::_0xD821056B9ACF8052(PLAYER::PLAYER_ID(), 1065353216);
  NETWORK::NETWORK_SET_FRIENDLY_FIRE_OPTION(true);
  PLAYER::SET_WANTED_LEVEL_MULTIPLIER(1f);
  if (!PED::IS_PED_INJURED(PLAYER::PLAYER_PED_ID()))
  {
    PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 108, false);
    PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 208, false);
    PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 122, false);
    PED::SET_PED_CAN_BE_TARGETTED(PLAYER::PLAYER_PED_ID(), true);
    ENTITY::SET_ENTITY_CAN_BE_DAMAGED(PLAYER::PLAYER_PED_ID(), true);
  }
  if (((((func_755("MP_SR_HELP_1") || func_755("MP_SR_HELP_2")) || func_755("MP_SR_HELP_3")) || func_755("MP_SR_HELP_4")) || func_755("MP_SR_HELP_5")) || func_755("MP_SR_IN_USE"))
  {
    HUD::CLEAR_HELP(1);
  }
  func_905();
}