// exile3.ysc @ L141703
void func_1039()
{
  if (ENTITY::IS_ENTITY_ATTACHED(PLAYER::PLAYER_PED_ID()))
  {
    if (!WEAPON::GET_IS_PED_GADGET_EQUIPPED(PLAYER::PLAYER_PED_ID(), joaat("GADGET_PARACHUTE")))
    {
      if (PED::GET_VEHICLE_PED_IS_USING(PLAYER::PLAYER_PED_ID()) == 0)
      {
        TASK::CLEAR_PED_TASKS(PLAYER::PLAYER_PED_ID());
        ENTITY::DETACH_ENTITY(PLAYER::PLAYER_PED_ID(), 1, true);
      }
    }
  }
  if (OBJECT::DOES_RAYFIRE_MAP_OBJECT_EXIST(uLocal_698))
  {
    OBJECT::SET_STATE_OF_RAYFIRE_MAP_OBJECT(uLocal_698, 11);
  }
  PLAYER::SET_PLAYER_FORCED_AIM(PLAYER::PLAYER_ID(), 0);
  PATHFIND::SET_GPS_DISABLED_ZONE(0f, 0f, 0f, 0f, 0f, 0f);
  func_1042();
  PLAYER::SET_PLAYER_CONTROL(PLAYER::PLAYER_ID(), true, 0);
  PED::SET_PED_CAN_SWITCH_WEAPON(PLAYER::PLAYER_PED_ID(), true);
  func_7(0, 1, 1, 0, 0, 0);
  func_1040();
}