// am_mp_property_int.ysc @ L265312
void func_2911()
{
  if (((((((!func_7268(&Global_2540121) && !NETWORK::NETWORK_IS_PLAYER_FADING(PLAYER::PLAYER_ID())) && !func_1944()) && !func_3191(PLAYER::PLAYER_ID(), 0)) && !CAM::IS_SCREEN_FADED_OUT()) && ENTITY::GET_ENTITY_ALPHA(PLAYER::PLAYER_PED_ID()) == 0) && PLAYER::IS_PLAYER_CONTROL_ON(PLAYER::PLAYER_ID())) && !func_3424())
  {
    ENTITY::SET_ENTITY_ALPHA(PLAYER::PLAYER_PED_ID(), 255, false);
  }
}