// fm_capture_creator.c @ L275838
void func_2819(vector3 vParam0, vector3 vParam1, float fParam2, int iParam3, int iParam4, int iParam5, int iParam6, int iParam7, bool bParam8)
{
  if (bParam8)
  {
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
    GRAPHICS::DRAW_POLY(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam1.z, vParam1.x, vParam1.y, vParam1.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, iParam6);
  }
  if (iParam7 || bParam8 == 0)
  {
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam0.x, vParam0.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), (fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
    GRAPHICS::DRAW_LINE(OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam0.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), OBJECT::_GET_OBJECT_OFFSET_FROM_COORDS(vParam1.x, vParam1.y, vParam1.z, func_2820(vParam0.x, vParam0.y, vParam0.z, vParam1.x, vParam1.y, vParam0.z), -(fParam2 / 2f), 0f, 0f), iParam3, iParam4, iParam5, 255);
  }
}