// jewelry_heist.c @ L127664
void func_888()
{
  if (!VEHICLE::HAS_VEHICLE_RECORDING_BEEN_LOADED(722, "JHUBER"))
  {
  }
  PLAYER::SET_PLAYER_CONTROL(PLAYER::PLAYER_ID(), false, 0);
  if (ENTITY::DOES_ENTITY_EXIST(iLocal_456[2]))
  {
    if (!ENTITY::IS_ENTITY_DEAD(iLocal_456[2], 0))
    {
      if (VEHICLE::IS_PLAYBACK_GOING_ON_FOR_VEHICLE(iLocal_456[2]))
      {
        VEHICLE::STOP_PLAYBACK_RECORDED_VEHICLE(iLocal_456[2]);
      }
      VEHICLE::START_PLAYBACK_RECORDED_VEHICLE_USING_AI(iLocal_456[2], 722, "JHUBER", fLocal_2000, 262144);
      VEHICLE::SKIP_TIME_IN_PLAYBACK_RECORDED_VEHICLE(iLocal_456[2], fLocal_1999);
      VEHICLE::SET_PLAYBACK_SPEED(iLocal_456[2], fLocal_2001);
      VEHICLE::SET_PLAYBACK_TO_USE_AI_TRY_TO_REVERT_BACK_LATER(iLocal_456[2], iLocal_2002, 262144, 0);
    }
  }
}