// agency_heist3a.c @ L140455
void func_1036()
{
  func_468(&uLocal_2277, 1, 0, "franklin", 0, 1);
  STREAMING::REQUEST_MODEL(func_536(0));
  STREAMING::REQUEST_MODEL(func_536(1));
  STREAMING::REQUEST_MODEL(Local_348[0 /*32*/].f_1);
  func_629(PLAYER::PLAYER_PED_ID(), 3);
  STREAMING::REQUEST_MODEL(Local_61.f_1);
  STREAMING::REQUEST_MODEL(joaat("prop_phone_ing"));
  STREAMING::REQUEST_ANIM_DICT(sLocal_2537);
  STREAMING::REQUEST_ANIM_DICT(sLocal_2539);
  VEHICLE::REQUEST_VEHICLE_RECORDING(2, "lkagency3a");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_crew_0_0");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_crew_1_0");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_0");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_1");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_2");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_3");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_4");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_5");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_michael_6");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_ambient_0");
  TASK::REQUEST_WAYPOINT_RECORDING("agency3a_ambient_1");
  AUDIO::RELEASE_NAMED_SCRIPT_AUDIO_BANK("SCRIPT\FBI_HEIST_S4_PLANT_BOMBS");
  AUDIO::REQUEST_SCRIPT_AUDIO_BANK("SCRIPT\FBI_Heist_5_Finale_02", false, -1);
  if (!iLocal_1954)
  {
    STREAMING::PREFETCH_SRL(sLocal_2541);
    STREAMING::_0xBEB2D9A1D9A8F55A(4, 4, 4, 4);
    STREAMING::_0xF8155A7F03DDFC8E(2);
    iLocal_1954 = 1;
  }
}