// freemode.c @ L166448
void func_2205()
{
  int iVar0;
  
  if (func_2194(PLAYER::PLAYER_ID(), 8))
  {
    return;
  }
  iVar0 = ENTITY::GET_ENTITY_MAX_HEALTH(PLAYER::PLAYER_PED_ID());
  ENTITY::SET_ENTITY_HEALTH(PLAYER::PLAYER_PED_ID(), func_2207(iVar0), 0);
  PLAYER::SET_PLAYER_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), Global_262145.f_24716);
  PLAYER::SET_PLAYER_HEALTH_RECHARGE_MULTIPLIER(PLAYER::PLAYER_ID(), Global_262145.f_24719);
  PLAYER::_SET_PLAYER_HEALTH_RECHARGE_LIMIT(PLAYER::PLAYER_ID(), Global_262145.f_24720);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 410, true);
  PED::SET_PED_CONFIG_FLAG(PLAYER::PLAYER_PED_ID(), 416, true);
  if (Global_262145.f_24724)
  {
    PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 5f, 1);
  }
  if (Global_262145.f_24717)
  {
    PED::SET_PED_SUFFERS_CRITICAL_HITS(PLAYER::PLAYER_PED_ID(), 0);
  }
  PLAYER::_SET_SPECIAL_ABILITY(PLAYER::PLAYER_ID(), 4);
  PLAYER::_SPECIAL_ABILITY_ACTIVATE(PLAYER::PLAYER_ID());
  HUD::_SET_ABILITY_BAR_VISIBILITY_IN_MULTIPLAYER(1);
  func_2206(8);
}