// family1.ysc @ L29747
void func_473()
{
  if (!ENTITY::IS_ENTITY_DEAD(iLocal_345, 0))
  {
    VEHICLE::UNPAUSE_PLAYBACK_RECORDED_VEHICLE(iLocal_345);
  }
  if (!ENTITY::IS_ENTITY_DEAD(iLocal_346, 0))
  {
    VEHICLE::UNPAUSE_PLAYBACK_RECORDED_VEHICLE(iLocal_346);
  }
  if (!ENTITY::IS_ENTITY_DEAD(iLocal_54, 0))
  {
    VEHICLE::UNPAUSE_PLAYBACK_RECORDED_VEHICLE(iLocal_54);
  }
  if (!ENTITY::IS_ENTITY_DEAD(iLocal_55, 0))
  {
    VEHICLE::UNPAUSE_PLAYBACK_RECORDED_VEHICLE(iLocal_55);
  }
}