// fm_deathmatch_controler.ysc @ L467294
void func_7549()
{
  if (!PED::IS_PED_INJURED(PLAYER::PLAYER_PED_ID()) && PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0))
  {
    if (NETWORK::NETWORK_IS_LOCAL_PLAYER_INVINCIBLE())
    {
      PAD::DISABLE_CONTROL_ACTION(0, 69, 1);
      PAD::DISABLE_CONTROL_ACTION(0, 70, 1);
      PAD::DISABLE_CONTROL_ACTION(0, 68, 1);
      PAD::DISABLE_CONTROL_ACTION(0, 345, 1);
      PAD::DISABLE_CONTROL_ACTION(0, 346, 1);
      PAD::DISABLE_CONTROL_ACTION(0, 347, 1);
    }
  }
}