// fbi5a.ysc @ L133476
void func_914()
{
  STREAMING::REQUEST_MODEL(vLocal_251.z);
  STREAMING::REQUEST_MODEL(vLocal_273.z);
  STREAMING::REQUEST_MODEL(Local_201.f_2);
  STREAMING::REQUEST_MODEL(vLocal_207.z);
  STREAMING::REQUEST_MODEL(Local_170.f_2);
  STREAMING::REQUEST_MODEL(Local_188.f_2);
  STREAMING::REQUEST_MODEL(Local_194.f_2);
  STREAMING::REQUEST_MODEL(Local_182.f_2);
  STREAMING::REQUEST_COLLISION_FOR_MODEL(Local_182.f_2);
  STREAMING::REQUEST_MODEL(Local_380.f_2);
  STREAMING::REQUEST_MODEL(joaat("prop_boxpile_02b"));
  STREAMING::REQUEST_ANIM_DICT("missfbi5ig_15");
  VEHICLE::REQUEST_VEHICLE_RECORDING(Local_386[0 /*15*/].f_13, "lkfbi5a");
  VEHICLE::REQUEST_VEHICLE_RECORDING(Local_386[1 /*15*/].f_13, "lkfbi5a");
  VEHICLE::REQUEST_VEHICLE_RECORDING(Local_386[2 /*15*/].f_13, "lkfbi5a");
  AUDIO::REQUEST_SCRIPT_AUDIO_BANK("SCRIPT\FBI_05_GRAB_TOXIN", false, -1);
  TASK::REQUEST_WAYPOINT_RECORDING("fbi5_dave_1");
  AUDIO::PREPARE_MUSIC_EVENT("FBI5A_LIFT_EXIT");
}