// agency_heist2.ysc @ L949
void func_13(int iParam0)
{
  if (ENTITY::DOES_ENTITY_EXIST(iLocal_82))
  {
    OBJECT::DELETE_OBJECT(&iLocal_82);
  }
  iLocal_82 = WEAPON::GET_WEAPON_OBJECT_FROM_PED(iParam0, 0);
  if (ENTITY::DOES_ENTITY_EXIST(iLocal_82))
  {
    PHYSICS::ACTIVATE_PHYSICS(iLocal_82);
  }
  else
  {
    iLocal_82 = WEAPON::CREATE_WEAPON_OBJECT(joaat("WEAPON_BRIEFCASE_02"), -1, ENTITY::GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(iLocal_79, -1f, 0f, 0f), 1, 1065353216, 0, 0, 1);
    PHYSICS::ACTIVATE_PHYSICS(iLocal_82);
  }
  WEAPON::REMOVE_WEAPON_FROM_PED(iParam0, joaat("WEAPON_BRIEFCASE_02"));
}