// freemode.c @ L804986
void func_11574(bool bParam0)
{
  GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(19, "FADE_BAR_OUT");
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_BOOL(bParam0);
  GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
}