// am_mp_defunct_base.c @ L288953
void func_4344(var uParam0)
{
  int iVar0;
  int iVar1;
  
  PATHFIND::GET_STREET_NAME_AT_COORD(CAM::GET_FINAL_RENDERED_CAM_COORD(), &iVar0, &iVar1);
  if (iVar1 != 0)
  {
    GRAPHICS::BEGIN_TEXT_COMMAND_SCALEFORM_STRING("STRTNM2");
    HUD::ADD_TEXT_COMPONENT_SUBSTRING_TEXT_LABEL_HASH_KEY(iVar0);
    HUD::ADD_TEXT_COMPONENT_SUBSTRING_TEXT_LABEL_HASH_KEY(iVar1);
    GRAPHICS::END_TEXT_COMMAND_SCALEFORM_STRING();
  }
  else if (iVar0 != 0)
  {
    GRAPHICS::BEGIN_TEXT_COMMAND_SCALEFORM_STRING("STRTNM1");
    HUD::ADD_TEXT_COMPONENT_SUBSTRING_TEXT_LABEL_HASH_KEY(iVar0);
    GRAPHICS::END_TEXT_COMMAND_SCALEFORM_STRING();
  }
  else
  {
    func_387(NETWORK::GET_TIME_AS_STRING(NETWORK::GET_NETWORK_TIME()));
  }
  uParam0->f_47.f_2165 = 8000;
  uParam0->f_47.f_2162++;
}