// am_mp_arena_box.ysc @ L111364
void func_1132(bool bParam0)
{
  if (bParam0)
  {
    func_364(1);
    func_367(1);
  }
  if (!PLAYER::IS_SYSTEM_UI_BEING_DISPLAYED() && !HUD::IS_PAUSE_MENU_ACTIVE())
  {
    HUD::DISABLE_FRONTEND_THIS_FRAME();
    PAD::DISABLE_ALL_CONTROL_ACTIONS(0);
    PAD::ENABLE_ALL_CONTROL_ACTIONS(1);
    PAD::DISABLE_CONTROL_ACTION(2, 200, 1);
    PAD::DISABLE_CONTROL_ACTION(2, 199, 1);
    PAD::SET_INPUT_EXCLUSIVE(0, 200);
    PAD::SET_INPUT_EXCLUSIVE(2, 200);
    PAD::SET_INPUT_EXCLUSIVE(0, 199);
    PAD::SET_INPUT_EXCLUSIVE(2, 199);
    PAD::SET_INPUT_EXCLUSIVE(0, 201);
    PAD::SET_INPUT_EXCLUSIVE(0, 202);
  }
}