// am_mp_nightclub.c @ L314103
void func_4791(var uParam0)
{
  int iVar0;
  
  CAM::INVALIDATE_IDLE_CAM();
  HUD::HUD_FORCE_WEAPON_WHEEL(0);
  HUD::DISPLAY_AMMO_THIS_FRAME(0);
  HUD::HIDE_HUD_COMPONENT_THIS_FRAME(19);
  HUD::HIDE_HUD_COMPONENT_THIS_FRAME(2);
  HUD::_HUD_WEAPON_WHEEL_IGNORE_SELECTION();
  func_4459();
  func_493(0);
  if (WEAPON::GET_CURRENT_PED_WEAPON(PLAYER::PLAYER_PED_ID(), &iVar0, 1) && iVar0 != joaat("WEAPON_UNARMED"))
  {
    WEAPON::SET_CURRENT_PED_WEAPON(PLAYER::PLAYER_PED_ID(), joaat("WEAPON_UNARMED"), true);
  }
  PAD::DISABLE_CONTROL_ACTION(0, 37, 1);
  func_4009(1);
  func_282();
  PAD::DISABLE_CONTROL_ACTION(0, 20, 1);
  if (!HUD::IS_RADAR_HIDDEN())
  {
    MISC::SET_BIT(&(uParam0->f_4), 11);
    HUD::DISPLAY_RADAR(false);
  }
  HUD::THEFEED_HIDE_THIS_FRAME();
  HUD::THEFEED_FLUSH_QUEUE();
}