// fmmc_launcher.c @ L386649
void func_5984(int iParam0)
{
  if (GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD_ON_FRONTEND("DISPLAY_DATA_SLOT"))
  {
    GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(iParam0);
    GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
  }
}