// am_bru_box.c @ L8815
void func_229()
{
  if (MISC::IS_BIT_SET(iLocal_63, 4))
  {
    PLAYER::SET_PLAYER_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 0.72f);
    PLAYER::SET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER(PLAYER::PLAYER_ID(), 1f, 1);
    PLAYER::SET_PLAYER_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 1f);
    PLAYER::SET_PLAYER_MELEE_WEAPON_DEFENSE_MODIFIER(PLAYER::PLAYER_ID(), 1f);
    func_230(1);
    MISC::CLEAR_BIT(&iLocal_63, 5);
    MISC::CLEAR_BIT(&iLocal_63, 7);
    MISC::CLEAR_BIT(&iLocal_63, 4);
  }
}