// arena_carmod.c @ L10267
void func_139(int iParam0)
{
  if (GRAPHICS::DOES_VEHICLE_HAVE_CREW_EMBLEM(iParam0, 0))
  {
    GRAPHICS::REMOVE_VEHICLE_CREW_EMBLEM(iParam0, 0);
  }
  if (GRAPHICS::DOES_VEHICLE_HAVE_CREW_EMBLEM(iParam0, 1))
  {
    GRAPHICS::REMOVE_VEHICLE_CREW_EMBLEM(iParam0, 1);
  }
}