// am_armwrestling.ysc @ L117776
void func_722(var uParam0, float fParam1)
{
  GRAPHICS::BEGIN_SCALEFORM_MOVIE_METHOD(*uParam0, "SHARD_ANIM_OUT");
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(uParam0->f_9);
  GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_FLOAT(fParam1);
  GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
}