// rural_bank_heist.c @ L126679
void func_907()
{
  if (PLAYER::IS_PLAYER_PLAYING(PLAYER::PLAYER_ID()))
  {
    if (ENTITY::GET_ENTITY_MODEL(PLAYER::PLAYER_PED_ID()) != func_108(1))
    {
      PAD::DISABLE_CONTROL_ACTION(0, 22, 1);
      PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 102, true);
      PED::SET_PED_ALLOWED_TO_DUCK(PLAYER::PLAYER_PED_ID(), 0);
    }
    else
    {
      PED::SET_PED_ALLOWED_TO_DUCK(PLAYER::PLAYER_PED_ID(), 1);
    }
    if (!iLocal_77 != PED::GET_PED_RELATIONSHIP_GROUP_HASH(PLAYER::PLAYER_PED_ID()))
    {
      PED::SET_PED_RELATIONSHIP_GROUP_HASH(PLAYER::PLAYER_PED_ID(), iLocal_77);
    }
    PED::SET_PED_STEALTH_MOVEMENT(PLAYER::PLAYER_PED_ID(), 0, 0);
    PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 224, true);
    PED::SET_PED_RESET_FLAG(PLAYER::PLAYER_PED_ID(), 200, true);
    PLAYER::_0xDC64D2C53493ED12(PLAYER::PLAYER_ID());
  }
}