// fm_mission_controller.c @ L324848
void func_4466()
{
  if (!func_4467() && !CAM::IS_CINEMATIC_CAM_RENDERING())
  {
    iLocal_6986 = CAM::CREATE_CAM_WITH_PARAMS("default_scripted_camera", CAM::GET_FINAL_RENDERED_CAM_COORD(), CAM::GET_FINAL_RENDERED_CAM_ROT(2), CAM::GET_FINAL_RENDERED_CAM_FOV(), 0, 2);
    CAM::SET_CAM_NEAR_CLIP(iLocal_6986, CAM::GET_FINAL_RENDERED_CAM_NEAR_CLIP());
    CAM::SET_CAM_FAR_CLIP(iLocal_6986, CAM::GET_FINAL_RENDERED_CAM_FAR_CLIP());
    CAM::SET_CAM_MOTION_BLUR_STRENGTH(iLocal_6986, CAM::GET_FINAL_RENDERED_CAM_MOTION_BLUR_STRENGTH());
    CAM::SET_CAM_ACTIVE(iLocal_6986, true);
    CAM::RENDER_SCRIPT_CAMS(true, false, 3000, 1, 0, 0);
  }
}