// fm_bj_race_controler.c @ L253953
void func_3153()
{
  PAD::DISABLE_CONTROL_ACTION(0, 25, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 69, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 70, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 114, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 68, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 24, 1);
  PAD::DISABLE_CONTROL_ACTION(0, 257, 1);
  PAD::DISABLE_CONTROL_ACTION(2, 230, 1);
  if (PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0))
  {
    if (VEHICLE::DOES_VEHICLE_HAVE_WEAPONS(PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), 0)))
    {
      VEHICLE::DISABLE_VEHICLE_WEAPON(0, joaat("VEHICLE_WEAPON_PLAYER_LASER"), PED::GET_VEHICLE_PED_IS_IN(PLAYER::PLAYER_PED_ID(), 0), PLAYER::PLAYER_PED_ID());
    }
  }
}